---
name: Auto Blog
on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Generate new blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: |
          python scripts/rebuild_index.py
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown
    
      - name: Cleanup posts older than 60 days
        env:
          CUTOFF_DAYS: "60"
          KEEP_MIN: "20"
        run: |
          python scripts/cleanup_old_posts.py
      - name: Commit & push
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(blog): auto post" || echo "No changes to commit"
          git push
